version: '3'
services:
 php:
  image: php:7.4-apache
  container_name: kamome_php
  ports:
   - "8006:80"
  volumes: 
   - ./kamome_site:/var/www/html/kamome_site
  depends_on:
   - db

 db:
  image: mysql:5.7
  platform: linux/amd64
  container_name: kamome_db
  ports:
   - "3304:3306"
  volumes:
   - ./kamome_db:/lib/bin/mysql/kamome_db
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: kamomedb
   MYSQL_USER: user
   MYSQL_PASSWORD: password

